# Template C++ Application

# This template allows you to validate your C++ application.
# The workflow allows running tests and code linting on the default branch.


image: nvidia/cuda:10.1-devel-ubuntu18.04

pipelines:
  default:
    - parallel:
        - step:
            name: Build
            script:
              - apt update && apt install -y cmake
              - mkdir build && cd build
              - cmake ..
              - make
